package com.shop.enums;

public enum BotState {
    AWAITING_COMMAND,
    AWAITING_LOGIN_USERNAME,
    AWAITING_LOGIN_PASSWORD,
    AWAITING_REGISTER_FULLNAME,
    AWAITING_REGISTER_USERNAME,
    AWAITING_REGISTER_PHONE,
    AWAITING_REGISTER_PASSWORD,
    AUTHENTICATED
}
